### ISSUE TITLE
How to read file header without streaming whole file (how to end stream after reading first line)

### ISSUE THREAD

**Issue by sbansal6** [C2FO/fast-csv#110]
is there a way to end csv stream after reading first line. Basically all i wanna do is read file headers only.

**Comment by doug-martin** [comment]
Im not sure how you could easily do that. You could just read one record and ignore the rest of them but you would still have to wait for the whole file to process.

The issue is when streaming we get data in chunks which can contain 1 or more lines of data (maybe even partial lines). You might want to take a look at the `fs` node api to explore different options but it might not be really straight forward.

**Comment by StoilTodorov** [comment]
I had the same issue "just read first line" and after researching, I realized that there's not code ready for using.
Then I create the next code:

    var fastCSV = require('fast-csv');
    var maxLineLength = 100; // you can define this from your requirements
    var readPartOfFile = maxLineLength * 2; // you can multiply by your factor more than 1 :)
    var stream = fs.createReadStream('my.csv', {start: 0, end: readPartOfFile });
    var csvStream = fastCSV.fromStream(stream);
    var line = 0;
    csvStream.on("data", function (data) {
        if ( line === 0 ) {
            callback(data);    // or do what will do
        }
        line++;
    });
    csvStream.on("end", function() {
        console.log('Reading for first line: ' + line + ' lines.');
    });

**Comment by doug-martin** [comment]
Doing some house cleaning.
