### ISSUE TITLE
CSV doesn't print 0 if it's first digit of number in cell

### ISSUE THREAD

**Issue by jediyozh** [C2FO/fast-csv#203]
I'm converting array of objects to scv and if value of some key in object starts with 0 such as "03246", I get only "3246" in csv file.

**Comment by jkrenge** [comment]
Make sure that you're writing a string to the CSV, numbers itself don't have leading 0s. So you could try something like that when passing your object to fast-csv:

```
{
  somekey: number + '',
  ..
}
```

The `+ ''` casts the result to a string by appending basically an empty string.

**Comment by thaiat** [comment]
unfortunately the solution proposed by @jkrenge does not work...

**Comment by manifestinteractive** [comment]
@JediYozh this is actually an issue with Excel, not this library.  You need to set the column type for the text to "Zip Code" as Excel will try to display it as a number, which is incorrect.  So that data is there, it's just being displayed incorrectly.

**Here is the setting you need to change:**

![screenshot 2018-06-08 at 3 51 57 pm](https://user-images.githubusercontent.com/508411/41178014-046cf8a8-6b34-11e8-8330-984b297aaa01.png)

Once you do this, it will show the zero leading numbers.

**Comment by doug-martin** [comment]
@jkrenge is correct its because your passing in numbers, a leading 0 on a number is actual treated as an octal in JS see https://stackoverflow.com/questions/6505033/number-with-leading-zero-in-javascript/28354557#28354557

Here is an example where the numbers are strings and it preserves the leading zeros.
```js
const rows = [
    { foo: '01234' },
    { foo: '03456' },
];

csv
    .write(rows, { headers: true })
    .pipe(process.stdout);
```

Output:
```
foo
01234
03456
```

Here is an example with a leading zero that is a number, note how the output is a completely different number because its treated as an octal.

```js
const rows = [
    { foo: 01234 },
    { foo: 03456 },
];

csv
    .write(rows, { headers: true })
    .pipe(process.stdout);
```
Output:
```
foo
668
1838
```
