### ISSUE TITLE
Implementing transform with write and read streams

### ISSUE THREAD

**Issue by RokasDie** [C2FO/fast-csv#292]
Hello,

I may be lacking some in depth understanding of streams in general. However, I would like to know how efficiently what I need should work.

I want to implement so that a csv file would be read, then to each row a query to the database (or api) is made and data is attached. After that the row with attached data is written to a new csv file.

Here is my implementation:

```
const fs = require("fs");
const csv = require("fast-csv");
const delay = t => new Promise(resolve => setTimeout(resolve, t));


const asyncFunction = async (row, csvStream) => {
  // Imitate some stuff with database
  await delay(1200);
  row.data = "data";
  csvStream.write(row);
};

const array = [];

const csvStream = csv.format({ headers: true });

const writeStream = fs.createWriteStream("output.csv");

csvStream.pipe(writeStream).on("finish", () => {
  console.log("End of writing");
});
fs.createReadStream("input.csv")
  .pipe(csv.parse({ headers: true }))
  .transform(async function(row, next) {
    array.push(asyncFunction(row, csvStream));
    next();
  })
  .on("finish", function() {
    console.log("finished reading file");
  //Wait for all database requests and writings to be finished to close write stream
    Promise.all(array).then(() => {
      csvStream.end();
      console.log("finished writing file");
    });
  });
```

Particularly I would like to know are there ways to optimize what I am doing here, because I feel that I am missing something important on how this library can be used for these type of cases

Regards,
Rokas

**Comment by doug-martin** [comment]
@RokasDie I think I can be of some help.

First, your `array.push(asyncFunction(row, csvStream));` should call next when done. If `ascynFunction` is returning a `Promise` then you could use the following

```js
asyncFunction(row, csvStream)
  .then((result) => next(null, result))
  .catch(err => next(err))
```

However, this will cause issues. First if your csv is large `fast-csv` will keep parsing and you could OOM if the csv is large. Second, you could wait a long time for your db operations to finish because you are doing them one at a time.

A better option would be to create a custom `Transform` stream, grouping your operations into batches. See https://gist.github.com/doug-martin/b434a04f164c81da82165f4adcb144ec

You should be able to expand on the example gist, but take a look at the [`_transform`](https://gist.github.com/doug-martin/b434a04f164c81da82165f4adcb144ec) and [`_flush`](https://gist.github.com/doug-martin/b434a04f164c81da82165f4adcb144ec)
