### ISSUE TITLE
[Dependencies] @types/node should be a devDependency

### ISSUE THREAD

**Issue by jormaechea** [C2FO/fast-csv#471]
https://github.com/C2FO/fast-csv/blob/bbb783b68c651d607d8a9951aada3afdaea6d57e/packages/fast-csv/package.json#L39-L43

**Comment by doug-martin** [comment]
@jormaechea  the `@types/node` is required because it is used in a few places for example:

* https://github.com/C2FO/fast-csv/blob/master/packages/parse/src/index.ts#L15
* https://github.com/C2FO/fast-csv/blob/master/packages/format/src/index.ts#L34

Both of those declarations are part of the released packages in the definition files so it is a required dependency, otherwise anytime you installed the package you would also have to install the `@types/node` package. There are a lot of questions around this see the following as a few examples:

* https://stackoverflow.com/questions/45176661/how-do-i-decide-whether-types-goes-into-dependencies-or-devdependencies 
* https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html#dependencies
