### ISSUE TITLE
[BUG] end not called from readStream with parsing an trasform

### ISSUE THREAD

**Issue by Jcbobo** [C2FO/fast-csv#494]
**Describe the bug**
end method not being called when data end 

**Parsing or Formatting?**

 - [X] Formatting
 - [X] Parsing 

**To Reproduce**
1. Example file contents if applicable
simple ; separated (excel generated csv)
Update;Delete;
A;;
B;;
C;;

2. Example code to reproduce the issue.
```javascript
entry={path:'files/file.csv',name:'file.csv"}
fs.createReadStream(entry.path, "utf8")
.pipe(csv.parse({headers: true,delimiter:";"}))
.pipe(csv.format({headers: true,delimiter:";"}))
.transform((row, next) => ({fileInput: entry.name,
					startProcessingTime: new Date(),
					content: row,
					applicationName: baseMapping.applicationName
}))
 .transform((row, next) => {
 	doStuff(params).promise()
 		.then((res)=>next(null,sqsRes))
 		.catch(err =>next(err))
 })
.on("end", () => {
   console.log(`file: ${entry.name} processed`);
     fs.unlinkSync(entry.path)
     console.log("file");
});
```
**Expected behavior**
at the end of the transform (for all rows) the on('end') is called

**Desktop (please complete the following information):**
 - OS: [ MacOS]
 - Node Version v14.13.1]

**Additional context**
at beginning i was thinking that was related to promise doStuff but event commenting that still not call the end event

**Comment by doug-martin** [comment]
@Jcbobo this isn't a `fast-csv` issue but instead an issue with node.js and a lack of consistency of the events that are emitted. In your example if you change the `end` to a `finish` event it will be emitted as expected. This is because the formatter stream is essentially in a write only mode. If you added a `data` event listener like 

```
.pipe(csv.format({ headers: true, delimiter: ';' }))
 .on('data', (data) => console.log('data'))
```

The `end` event would be emitted because the stream is in read and write mode. 

https://github.com/nodejs/node/issues/21705 discusses this issue as well.
