### ISSUE TITLE
[BUG] out of heap

### ISSUE THREAD

**Issue by binary64** [C2FO/fast-csv#626]
```
    const outputFs = fs.createWriteStream('test.csv')
    csvStream = csv.format({ headers:true })
    csvStream.pipe(outputFs).on('end', () => process.exit())
    while (true) {
        console.log(Math.round(process.memoryUsage()['heapUsed'] / 1024/1024))
        csvStream.write({a:"b"})
    }
```

this code exchausts the heap and node eventually crashes

Any ideas how I can make the heap not grow forever here?

**Comment by doug-martin** [comment]
@binary64  the `while(true)` is blocking the event loop, not allowing any data to be written. If you make your loop async it should be fine. 

I know your example isn't a real world one but if you really wanted to infinitely write to the stream you could do 

```ts
const writeToCsv = (stream) => {
   console.log(Math.round(process.memoryUsage()['heapUsed'] / 1024/1024))
   csvStream.write({a:"b"})
   setImmediate(() => writeToCsv(stream));
}

const outputFs = fs.createWriteStream('test.csv')
csvStream = csv.format({ headers:true })
csvStream.pipe(outputFs).on('end', () => process.exit())
writeToCsv(csvStream);
```

In this example `end` will never be called because you are continually writing to the stream.
