### ISSUE TITLE
Slow performance generating CSV from array / object

### ISSUE THREAD

**Issue by brunorey** [C2FO/fast-csv#83]
Hi,

I am trying your library to write CSV data files from data I have in memory and found very slow performance. At first I thought it was a disk acces issue but then I coded a small benchmark separating csv generation from disk writing and found that the main delay is when the csv is generated.

I coded an alternative benchmark just nesting two FORs and appending commas and endlines and it was about 4 times faster.

*Mostly I'm interested in knowing if I'm doing something wrong in the way I'm using your lib or if this is just it's normal performance.*

You can see my tests here: http://pastebin.com/McwhxY9B , http://pastebin.com/cRKZRqp3 . It just writes 1 million rows with 4 32-bit integer each. Test data generation isn't optimal but it's enough for the purpose of this test, I think.

In my local computer I got about 8 seconds with the lib and 2 seconds with my alternative to generate the million rows. Tried several times and results were consistent. Time ratio (~4 to 1) was also consistent when testing with different number of rows.

**Comment by brunorey** [comment]
I'm running Kubuntu 14.10, using **fast-csv v0.5.4** and **nodejs v0.10.25**

**Comment by doug-martin** [comment]
So the generation will be slower than using for loops because the generation is asynchronous using streams so writing does not happen within a single event loop tick. Using for loops its all happening within the same tick. `fast-csv` is also doing considerably more processing on the input to ensure everything is escaped and formatted properly which could also lead to slower performance. I hope this helps clarify.

-Doug
